"""ADX identifier/reference checks independent of a connected ECU.

Known-answer vectors are from TunerPro's supplied TunerProELM327.adx, not
generated by this implementation. This catches the former sequential IDs.
"""
from pathlib import Path
import sys
import xml.etree.ElementTree as ET

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'tools'))
from tunerpro_logging import FLAGS, NARROWBAND_FLAGS, VALUES, identifier_hash, make


def test_identifier_hash_known_answers():
    expected={'FUELHISTO':0x931F314C,'BATVVAL':0xE32A726C,
              'MONITOR1':0xF9C5B75D,'MON2':0xAF63C8B9,
              'MAINDASH':0x7A2F048C,'MAINLIST':0x7F6896CC,
              'MONITOR':0xEFCE2DD1,'RPMMACRO':0xC5324AA3,
              'RPMREPLY':0x1E6CB0C2,'CTSREQ':0xF0C79B96,
              'TPR':0xCD444C7B,'TPM':0xCD4451DB}
    for name,value in expected.items():
        assert identifier_hash(name)==value,(name,value)


def test_polling_and_display_references():
    root=make().getroot()
    objects={n.get('id'):n for n in root if n.get('id')}
    by_hash={int(n.get('idhash'),0):n for n in objects.values()}
    assert len(objects)==len(by_hash)==2+1+len(VALUES)+len(FLAGS)+len(NARROWBAND_FLAGS)+3
    monitor=root.findtext('ADXHEADER/monitorcmd')
    macro=by_hash[identifier_hash(monitor)]
    assert macro.tag=='ADXMACRO'
    commands=[by_hash[identifier_hash(n.get('commandID'))] for n in macro.findall('NODE')]
    # Extension 2 carries inhibits and DTC counts: one command per cycle.
    assert [n.tag for n in commands]==['ADXCSENDCOMMAND','ADXCLISTENPACKET']
    send,receive=commands
    assert bytes.fromhex(send.findtext('bytestring'))==bytes((0xaa,1,0x10,0x11))
    assert int(receive.findtext('packetbodylength'))==98+3
    assert int(receive.findtext('packetoffsetinbody'))==2
    assert int(receive.findtext('packetsize'))==98
    # TunerPro's successful-reply handler tests this bit before publishing
    # values, logging or incrementing its displayed packet-rate counter.
    assert int(receive.get('flags'),0)&1
    for node in root.findall('ADXVALUE'):
        parent=by_hash[int(node.findtext('parentcmdidhash'),0)]
        assert parent is receive
        assert int(node.findtext('packetoffset'),0)+int(node.findtext('sizeinbits'))//8<=98
    for node in root.findall('ADXBITMASK'):
        assert by_hash[int(node.findtext('parentcmdidhash'),0)] is receive
        mask=int(node.findtext('operand'),0)
        assert int(node.findtext('packetoffset'),0)<98 and mask<256 and bin(mask).count('1')==1
        assert node.findtext('bitop')=='AND' and int(node.findtext('result'),0)==mask
    for name,tags,count in [('ENGINE',('ADXVALUE','ADXBITMASK'),len(VALUES)+len(NARROWBAND_FLAGS)),
                            ('STATUS',('ADXBITMASK',),len(FLAGS)),('TPS_CAL',('ADXVALUE',),3)]:
        view=objects[name]
        assert len(view.findall('ADXLVENTRY'))==int(view.findtext('entrycount'))==count
        for entry in view.findall('ADXLVENTRY'):
            assert by_hash[int(entry.get('itemidhash'),0)].tag in tags
    for name,mask in [('NB_LEAN',1),('NB_STOICH',2),('NB_RICH',4)]:
        node=objects[name]
        assert int(node.findtext('packetoffset'),0)==93
        assert int(node.findtext('operand'),0)==mask
        assert any(e.get('itemidhash')==node.get('idhash') for e in objects['ENGINE'].findall('ADXLVENTRY'))
    assert not any('quality' in n.get('title','').lower() for n in objects.values())
    dependency=root.find('ADXHEADER/DEPENDSONPLUGIN')
    assert dependency.get('filename')=='TU744.dll' and dependency.get('minverminor')=='6'
    assert int(objects['TPS_ADC'].findtext('packetoffset'),0)==54
    assert int(objects['TPS_ADC'].findtext('sizeinbits'))==16
    shipped=ET.parse(ROOT/'tunerpro/TU744_schema5.adx').getroot()
    assert ET.tostring(shipped)==ET.tostring(root), 'ADX is stale; run tools/tunerpro_logging.py'


def test_wideband_display_packet_examples():
    root=make().getroot()
    objects={n.get('id'):n for n in root if n.get('id')}
    refs={e.get('itemidhash') for e in objects['ENGINE'].findall('ADXLVENTRY')}
    # Firmware monitor contract: AFR10 at 15, target AFR10 at 16,
    # raw oxygen ADC as a big-endian word at 62. Distinct neighbouring bytes
    # expose offset and byte-order mistakes.
    packet=bytearray([0xA5]*98)
    packet[15]=147
    packet[16]=132
    packet[62:64]=(512).to_bytes(2,'big')
    def decode(name):
        node=objects[name]
        assert node.get('idhash') in refs
        at=int(node.findtext('packetoffset'),0)
        size=int(node.findtext('sizeinbits'))//8
        raw=int.from_bytes(packet[at:at+size],'big')
        return eval(node.find('MATH').get('equation'),{'__builtins__':{}},{'X':raw})
    assert decode('AFR')==14.7
    assert decode('WB_LAMBDA')==1.0
    assert abs(decode('TARGET_LAMBDA')-0.8979591837)<1e-9
    assert abs(decode('O2_VOLTS')-2.5024437928)<1e-9
    packet[15]=118
    assert abs(decode('WB_LAMBDA')-0.8027210884)<1e-9
    packet[62:64]=(1023).to_bytes(2,'big')
    assert decode('O2_VOLTS')==5.0


if __name__=='__main__':
    test_identifier_hash_known_answers()
    test_polling_and_display_references()
    test_wideband_display_packet_examples()
    print('PASS official ADX hash vectors, polling/list references and wideband packet decoding')
