"""Import TU5JP ROM-derived event/subtype report labels, not generic guesses."""
import csv
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parents[2] / 'engines/TU5JP/defs/dtc_events.csv'
rows = []
for record in csv.DictReader(SOURCE.open(encoding='utf-8-sig')):
    for subtype in (1, 2, 4, 8):
        code = record[f'subtype_{subtype}_code']
        if code:
            description = record[f'subtype_{subtype}_description'] or 'Description unavailable'
            rows.append(f'    {{{int(record["event"], 16)}, {subtype}, {{{json.dumps(code)}, {json.dumps(description)}}}}},')
text = '''// Generated by tools/diagnostic_definition.py from TU5JP ROM report-table evidence.
#include "diagnostics.h"
namespace {
struct Entry { unsigned event, subtype; DtcLabel label; };
const Entry entries[]={
''' + '\n'.join(rows) + '''
};
}
DtcLabel LookupDtc(unsigned event,unsigned subtype) {
    for(const auto& e:entries) if(e.event==event && e.subtype==subtype) return e.label;
    return {nullptr,nullptr};
}
'''
target = ROOT / 'src/dtc_defs.cpp'
if '--check' in sys.argv:
    if not target.exists() or target.read_text(encoding='utf-8') != text:
        raise SystemExit('DTC definitions need regeneration')
else:
    target.write_text(text, encoding='utf-8')
print(f'PASS {len(rows)} ROM-derived event/subtype labels')
