"""Generate the desktop schema and validator from standalone firmware sources.

Run from any directory; --check verifies committed generated output.
The validator preserves each firmware predicate, replacing its early failure
with an issue so the desktop can present every failed rule.
"""
from pathlib import Path
import argparse
import ast
import json
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
FW = ROOT.parent
sys.path.insert(0, str(FW / 'tools'))
sys.dont_write_bytecode = True
import tunerpro_definition


def q(value):
    return json.dumps(value, ensure_ascii=True)


def linear(expr):
    tree = ast.parse(expr, mode='eval')
    assert all(isinstance(n, (ast.Expression, ast.BinOp, ast.UnaryOp, ast.Name,
                             ast.Load, ast.Constant, ast.Add, ast.Sub, ast.Mult,
                             ast.Div, ast.USub, ast.UAdd)) for n in ast.walk(tree))
    def at(x):
        return eval(compile(tree, '<xdf>', 'eval'), {'__builtins__': {}}, {'X': x})
    base, scale = at(0), at(1) - at(0)
    assert abs(at(17) - (base + 17 * scale)) < 1e-6
    return f'{float(scale)}f', f'{float(base)}f'


def generate():
    root = tunerpro_definition.generate(alpha_n=False).getroot()
    lines = ['// Generated by tools/wizard_definition.py; do not edit.', '#include "calibration.h"']
    axes = {}
    names = {0x400: 'RPM', 0x420: 'KPA', 0x440: 'TPS', 0x460: 'TEMP',
             0x610: 'IDLE_IGN_ERR', 0x740: 'ACCEL_RATE_X', 0x750: 'ACCEL_RATE_Y',
             0x789: 'ACCEL_AMOUNT_RPM'}
    def typ(d):
        return 'CellType::' + ('S' if int(d.get('mmedtypeflags', '0'), 0) & 1 else 'U') + ('16BE' if d.get('mmedelementsizebits') == '16' else '8')
    def axis(a):
        count = int(a.findtext('indexcount'))
        if count == 1:
            return 'nullptr'
        d = a.find('EMBEDDEDDATA')
        address = d.get('mmedaddress')
        labels = tuple(float(n.get('value') or i) for i, n in enumerate(a.findall('LABEL')))
        offset = int(address, 0) if address else -1
        key = (offset, count, labels)
        if key not in axes:
            suffix = names.get(offset, f'FIXED_{len(axes)}')
            if labels == tuple(range(4, 19, 2)): suffix = 'VOLTAGE'
            if len(labels) == 16 and labels[-1] == 1023: suffix = 'MAP_ADC'
            name = 'AXIS_' + suffix
            axes[key] = name
            fixed = 'nullptr'
            if offset < 0:
                fixed = name + '_VALUES'
                lines.append(f'static const float {fixed}[] = {{' + ', '.join(f'{x}f' for x in labels) + '};')
            lines.append(f'const AxisDef {name} = {{{q(suffix)}, {offset}, {count}, {typ(d)}, {q(a.findtext("units", ""))}, 1, 0, {fixed}}};')
        return '&' + axes[key]
    tables, scalars, flags = [], [], []
    deps = []
    dropdown_offsets = {0x5D8, 0x600}
    for n in root:
        if n.tag not in ('XDFTABLE', 'XDFCONSTANT', 'XDFFLAG'): continue
        name, desc = n.findtext('title'), n.findtext('description', '')
        cat = tunerpro_definition.CATEGORIES[int(n.find('CATEGORYMEM').get('category')) - 1]
        z = n.find("XDFAXIS[@id='z']") if n.tag == 'XDFTABLE' else n
        d = z.find('EMBEDDEDDATA'); offset = int(d.get('mmedaddress'), 0)
        common = f'{q(name)}, {q(cat)}, {offset}'
        if n.tag == 'XDFFLAG':
            if offset in dropdown_offsets: continue
            mask = int(n.findtext('mask'), 0)
            if offset == 0x7B4 and mask in (2, 4, 16, 32): continue
            flags.append(f'{{{common}, {mask}, "Off", "On", {q(desc)}}}')
        elif n.tag == 'XDFCONSTANT':
            if offset in dropdown_offsets: continue
            scale, translate = linear(n.find('MATH').get('equation'))
            scalars.append(f'{{{common}, {typ(d)}, {q(n.findtext("units", ""))}, {scale}, {translate}, {n.findtext("min")}, {n.findtext("max")}, {q(desc)}}}')
        else:
            x, y = axis(n.find("XDFAXIS[@id='x']")), axis(n.find("XDFAXIS[@id='y']"))
            if offset in (0, 0x100, 0x200): y = '&AXIS_LOAD'
            scale, translate = linear(z.find('MATH').get('equation'))
            tables.append(f'{{{common}, {d.get("mmedrowcount")}, {d.get("mmedcolcount")}, {typ(d)}, {q(z.findtext("units", ""))}, {scale}, {translate}, {x}, {y}, {z.findtext("min")}, {z.findtext("max")}, false, {q(desc)}}}')
        # Dependencies are keyed by byte offset, not display strings.
        def dep(control, mask, value, reason):
            deps.append(f'{{{offset}, {control}, {mask}, {value}, {q(reason)}}}')
        if cat == 'Closed loop (STFT)': dep(0x5D4, 32, 32, 'Enable closed-loop fuel trim')
        if offset in (0x601, 0x602, 0x8C1, 0x8CD, 0x926): dep(0x600, 255, 1, 'Select wideband oxygen input')
        if offset in (0x8C2, 0x8C3, 0x8C4, 0x8C7, 0x8C8, 0x8C9): dep(0x600, 255, 0, 'Select narrowband oxygen input')
        if offset in (0x928, 0x92A, 0x92C, 0x92E): dep(0x926, 255, 1, 'Enable wideband qualification')
        if offset in (0x630, 0x632): dep(0x5D8, 255, 1, 'Select PI idle control')
        if offset in (0x7B5, 0x7B7): dep(0x7B4, 1, 1, 'Enable soft rev limit')
        if offset in (0x5E7, 0x7AF, 0x8C5, 0x930, 0x932, 0x934): dep(0x5D4, 4, 4, 'Enable launch control')
        if offset in (0x7B8, 0x7B9, 0x936, 0x938, 0x939): dep(0x7B4, 64, 64, 'Enable anti-lag')
    lines.append('const AxisDef AXIS_LOAD = {"Load", -2, 16, CellType::U16BE, "kPa / TPS %", 1, 0};')
    for kind, entries in [('Table', tables), ('Scalar', scalars), ('Flag', flags)]:
        upper = kind.upper() + 'S'
        lines.append(f'static const {kind}Def {kind.lower()}Defs[] = {{\n' + ',\n'.join(entries) + '\n};')
        lines.append(f'const {kind}Def* ALL_{upper} = {kind.lower()}Defs;\nconst int NUM_{upper} = sizeof({kind.lower()}Defs)/sizeof({kind}Def);')
    lines += ['static const char* idle[] = {"Steps", "PI", "Ignition only"};',
              'static const char* oxygen[] = {"Narrowband", "Wideband"};',
              'static const char* cut[] = {"Fuel and spark", "Fuel", "Spark", "Fuel and spark"};',
              'static const DropdownDef dropdownDefs[] = {',
              '{"Idle mode", "Idle", 0x5D8, 255, 0, idle, 3, "Idle control strategy."},',
              '{"Oxygen input", "Oxygen sensor and wideband", 0x600, 255, 0, oxygen, 2, "Sensor input mode."},',
              '{"Rev-limit cut", "Rev limit and fuel cut", 0x7B4, 6, 1, cut, 4, "Cut outputs selected by the limiter."},',
              '{"Launch cut", "Launch and anti-lag", 0x7B4, 48, 4, cut, 4, "Cut outputs selected by launch control."}};',
              'const DropdownDef* ALL_DROPDOWNS = dropdownDefs;\nconst int NUM_DROPDOWNS = 4;',
              'const Dependency DEPENDENCIES[] = {\n' + ',\n'.join(sorted(set(deps))) + '\n};',
              'const int NUM_DEPENDENCIES = sizeof(DEPENDENCIES)/sizeof(Dependency);']
    return '\n'.join(lines) + '\n'


def validator():
    source = (FW / 'src/calibration.c').read_text()
    body = source.split('u8 cal_validate(const u8 *c, u16 *error) {', 1)[1].split('\nstatic void cal_touch', 1)[0]
    body = re.sub(r'return fail\(error, (.*?)\);', r'report(\1);', body)
    body = body.replace('    *error = (u16)sb;\n    return 1;', '    return issues;')
    defines = []
    for p in sorted((FW / 'include').glob('*.h')):
        for line in p.read_text().splitlines():
            if re.match(r'#define (CAL_|CFG_|EQUIP_|IAC_HOME)', line) and not line.startswith('#define CAL_SIZE '):
                defines.append(line)
    ranges = source.split('static const u16 structural_ranges[][2] = ', 1)[1].split(';', 1)[0]
    return '''// Generated from src/calibration.c; one issue for each failed firmware predicate.
#include "calibration_safety.h"
#include <cstdint>
#include <cstdio>
using u8 = uint8_t; using s8 = int8_t; using u16 = uint16_t;
using s16 = int16_t; using u32 = uint32_t;
static u16 get16(const u8* p) { return (p[0]<<8)|p[1]; }
''' + '\n'.join(defines) + '''
std::vector<CalibrationIssue> ValidateCalibration(const CalBuffer& cal) {
    std::vector<CalibrationIssue> issues;
    if (!cal.loaded) { issues.push_back({IssueSeverity::Error, "Load a calibration first", "unloaded"}); return issues; }
    const u8* c = cal.data;
    auto report = [&](int offset) {
        char id[32]; snprintf(id, sizeof(id), "rule-%03X", offset);
        std::string message = "Firmware validation failed at " + std::string(id + 5);
        CalibrationIssue issue{IssueSeverity::Error, message, id};
        for (int i=0; i<NUM_SCALARS; ++i) if (ALL_SCALARS[i].offset == offset) {
            issue.target=IssueTarget::Scalar; issue.targetIndex=i;
            issue.message += ": " + std::string(ALL_SCALARS[i].name);
            issue.allowed=ALL_SCALARS[i].description;
        }
        issues.push_back(issue);
    };
''' + body + '\nconst CalibrationRange STRUCTURAL_RANGES[] = ' + ranges + ''';
const int NUM_STRUCTURAL_RANGES = sizeof(STRUCTURAL_RANGES)/sizeof(CalibrationRange);
bool IsStructuralOffset(int offset) {
    for (const auto& r : STRUCTURAL_RANGES) if (offset >= r.start && offset < r.end) return true;
    return false;
}
'''


if __name__ == '__main__':
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, contents in [('cal_defs.cpp', generate()), ('cal_validate_generated.cpp', validator())]:
        p = ROOT / 'src' / name
        if args.check:
            assert p.read_text() == contents, f'{name} is stale'
        else:
            p.write_text(contents, encoding='utf-8')
