// Generated by tools/tunerpro_definition.py from the ROM report table
// (engines/TU5JP/defs/dtc_events.csv). Do not edit.
#pragma once
namespace tu5jp {
struct DtcEvent { unsigned char event; const char* code[4]; const char* text[4]; };
inline const DtcEvent dtc_events[]={
    {0x03,{"P0300","P0300","P0300","P0300"},{"Random/multiple cylinder misfire","Random/multiple cylinder misfire","Random/multiple cylinder misfire","Random/multiple cylinder misfire"}},
    {0x04,{"P0301","P0301","P0301","P0301"},{"Cylinder 1 misfire","Cylinder 1 misfire","Cylinder 1 misfire","Cylinder 1 misfire"}},
    {0x05,{"P0303","P0303","P0303","P0303"},{"Cylinder 3 misfire","Cylinder 3 misfire","Cylinder 3 misfire","Cylinder 3 misfire"}},
    {0x06,{"P0304","P0304","P0304","P0304"},{"Cylinder 4 misfire","Cylinder 4 misfire","Cylinder 4 misfire","Cylinder 4 misfire"}},
    {0x07,{"P0302","P0302","P0302","P0302"},{"Cylinder 2 misfire","Cylinder 2 misfire","Cylinder 2 misfire","Cylinder 2 misfire"}},
    {0x08,{"P0300","P0300","P0300","P0300"},{"Random/multiple cylinder misfire","Random/multiple cylinder misfire","Random/multiple cylinder misfire","Random/multiple cylinder misfire"}},
    {0x09,{"P0301","P0301","P0301","P0301"},{"Cylinder 1 misfire","Cylinder 1 misfire","Cylinder 1 misfire","Cylinder 1 misfire"}},
    {0x0A,{"P0303","P0303","P0303","P0303"},{"Cylinder 3 misfire","Cylinder 3 misfire","Cylinder 3 misfire","Cylinder 3 misfire"}},
    {0x0B,{"P0304","P0304","P0304","P0304"},{"Cylinder 4 misfire","Cylinder 4 misfire","Cylinder 4 misfire","Cylinder 4 misfire"}},
    {0x0C,{"P0302","P0302","P0302","P0302"},{"Cylinder 2 misfire","Cylinder 2 misfire","Cylinder 2 misfire","Cylinder 2 misfire"}},
    {0x0D,{"P0338","P0337","P0335","P0336"},{"Crankshaft position circuit high","Crankshaft position circuit low","Crankshaft position sensor circuit","Crankshaft position range/performance"}},
    {0x1A,{"P1327","P1327","P1327","P1327"},{"Cylinder phase detection (DEPHIA)","Cylinder phase detection (DEPHIA)","Cylinder phase detection (DEPHIA)","Cylinder phase detection (DEPHIA)"}},
    {0x1B,{"P0123","P0122","P0120","P0121"},{"Throttle position circuit high","Throttle position circuit low","Throttle position sensor circuit","Throttle position range/performance"}},
    {0x27,{"P0171","P0172","P0170","P0170"},{"System too lean","System too rich","Fuel trim malfunction","Fuel trim malfunction"}},
    {0x2D,{"P0130","P0130","P0130","P0130"},{"Upstream O2 sensor circuit","Upstream O2 sensor circuit","Upstream O2 sensor circuit","Upstream O2 sensor circuit"}},
    {0x3F,{"P0133","P0133","P0133","P0133"},{"Upstream O2 sensor slow response","Upstream O2 sensor slow response","Upstream O2 sensor slow response","Upstream O2 sensor slow response"}},
    {0x40,{"P0133","P0133","P0133","P0133"},{"Upstream O2 sensor slow response","Upstream O2 sensor slow response","Upstream O2 sensor slow response","Upstream O2 sensor slow response"}},
    {0x43,{"P0108","P0107","P0109","P0106"},{"MAP sensor circuit high","MAP sensor circuit low","MAP sensor circuit intermittent","MAP sensor range/performance"}},
    {0x45,{"P0132","P0131","P0134","P0130"},{"Upstream O2 sensor circuit high","Upstream O2 sensor circuit low","Upstream O2 sensor no activity","Upstream O2 sensor circuit"}},
    {0x4A,{"P0338","P0337","P0335","P0336"},{"Crankshaft position circuit high","Crankshaft position circuit low","Crankshaft position sensor circuit","Crankshaft position range/performance"}},
    {0x4B,{"P1327","P1327","P1327","P1327"},{"Cylinder phase detection (DEPHIA)","Cylinder phase detection (DEPHIA)","Cylinder phase detection (DEPHIA)","Cylinder phase detection (DEPHIA)"}},
    {0x4D,{"P1528","P1527","P1529","P1526"},{"Manufacturer specific - idle actuator circuit high","Manufacturer specific - idle actuator circuit low","Manufacturer specific - idle actuator range/performance","Manufacturer specific - idle actuator circuit"}},
    {0x50,{"P0606","P0606","P0606","P0606"},{"Internal control module processor fault","Internal control module processor fault","Internal control module processor fault","Internal control module processor fault"}},
    {0x56,{"P1525","P1525","P1524","P1523"},{"Manufacturer specific - idle actuator group","Manufacturer specific - idle actuator group","Manufacturer specific - idle actuator group","Manufacturer specific - idle actuator group"}},
    {0x5B,{"P0113","P0112","P0110","P0111"},{"Intake air temperature circuit high","Intake air temperature circuit low","Intake air temperature circuit","Intake air temperature range/performance"}},
    {0x61,{"P0118","P0117","P0115","P0116"},{"Coolant temperature circuit high","Coolant temperature circuit low","Coolant temperature circuit","Coolant temperature range/performance"}},
    {0x65,{"P0563","P0562","P0560","P0561"},{"System voltage high","System voltage low","System voltage malfunction","System voltage unstable"}},
    {0x68,{"P0503","P0502","P0500","P0501"},{"Vehicle speed sensor intermittent/high","Vehicle speed sensor circuit low","Vehicle speed sensor","Vehicle speed sensor range/performance"}},
};
}
