"""Extract immutable TU5JP diagnostic evidence; no invented P-code mapping."""
from pathlib import Path
import hashlib
import json
import struct
import sys

ROOT=Path(__file__).resolve().parents[1]
REPO=ROOT.parents[1]
sys.path.insert(0,str(REPO/'src'))
from c167re.fueling.operating_state import FuelCalibration
from c167re.analysis.dtcs import TU5JP_DYNAMIC_EVENT_RULES, event_callsites, recover_calls
from dtc_policy import policy_for

data=(REPO/'bins/M744_C167_FULL.bin').read_bytes()
cal=FuelCalibration(data)  # enforces exact SHA-256
rows=[struct.unpack_from('<4H',data,0x16682+8*i) for i in range(107)]
text=['/* Generated by tools/generate_oem.py; TU5JP ROM only. */','#include "ecu.h"','static const u16 report_words[107][4]={']
text += ['    {'+','.join(f'0x{x:04X}U' for x in row)+'},' for row in rows]
text += ['};', '''u16 dtc_report_word(u8 event,u8 subtype) {
    u8 index;
    if(event>=107)return 0;
    switch(subtype){case 1:index=0;break;case 2:index=1;break;case 4:index=2;break;case 8:index=3;break;default:return 0;}
    return report_words[event][index];
}
/* Callback-selection mask for 0x6A996. New/clear are exclusive; completion
   falls through to subtype comparison, so both latter bits may be set. */
u8 dtc_ingest_action(u16 old,u16 descriptor) {
    u8 action=0;
    if((descriptor&1U)&&(!(old&1U)||!(descriptor&0x1000U)))return DTC_INGEST_NEW;
    if(!(descriptor&1U)&&(old&1U))return DTC_INGEST_CLEAR;
    if((descriptor&2U)&&!(old&2U))action|=DTC_INGEST_COMPLETE;
    if((descriptor&1U)&&((descriptor^old)&0x0F00U))action|=DTC_INGEST_SUBTYPE;
    return action;
}''']
(ROOT/'src/oem_dtc.c').write_text('\n'.join(text)+'\n')
config=['/* Generated by tools/generate_oem.py; immutable TU5JP reference. */',
        '#include "oem.h"','const u8 oem_dtc_configs[38][14]={']
config += ['{'+','.join(str(v) for v in data[0x1D896+14*i:0x1D8A4+14*i])+'},' for i in range(38)]
config += ['};','const u16 oem_dtc_phase_addresses[7]={'+
           ','.join(f'0x{v:04X}U' for v in struct.unpack_from('<7H',data,0x16AB0))+'};']
config += ['const u8 oem_dtc_event_configs[107]={'+','.join(str(v) for v in data[0x1186F:0x118DA])+'};']
config += ['const u8 oem_dtc_event_counts[107]={'+','.join(str(v) for v in data[0x118DA:0x11945])+'};']
config += ['const u16 oem_dtc_drive_delay='+str(struct.unpack_from('<H',data,0x1D894)[0])+'U;']
config += ['const u8 oem_dtc_warmup_limits[3]={'+','.join(str(v) for v in data[0x11945:0x11948])+'};']
config += ['const u8 oem_readiness_limits[5]={'+','.join(str(v) for v in data[0x11949:0x1194E])+'};']
(ROOT/'src/oem_dtc_config.c').write_text('\n'.join(config)+'\n')
input_header=['/* Generated native input calibration; exact TU5JP image. */']
for name,offset in [('OEM_IAT_FALLBACK',0x19879),('OEM_IAT_LOW',0x1987A),
                    ('OEM_IAT_HIGH',0x1987B),('OEM_IAT_COOLANT_MAX',0x198A5),('OEM_IAT_DELAY',0x198A6)]:
    input_header.append(f'#define {name} {data[offset]}U')
for name,offset in [('OEM_IAT_FILTER',0x1D892),('OEM_CONTEXT_SPEED_SCALE',0x14B5C)]:
    input_header.append(f'#define {name} {cal.word(offset)}U')
for name,offset in [('iat_raw',0x1987C),('crank_upper',0x18125),('crank_lower',0x1811E)]:
    input_header.append(f'static const u8 {name}[256]={{')
    values=[cal.curve(offset,i) for i in range(256)]
    input_header += [','.join(str(v) for v in values[i:i+24])+',' for i in range(0,256,24)]
    input_header.append('};')
(ROOT/'include/oem_input_data.h').write_text('\n'.join(input_header)+'\n')
voltage_header=['/* Immutable TU5JP calibration bytes at ROM115FE..11603; generate_oem.py. */']
for i,name in enumerate(['DELAY','COUNT','FALLBACK','LOW','INVALID','HIGH']):
    voltage_header.append(f'#define OEM_VOLTAGE_{name} {data[0x115FE+i]}U')
(ROOT/'include/oem_voltage_data.h').write_text('\n'.join(voltage_header)+'\n')
vss_header=['/* Immutable TU5JP ROM1001F..10026,147FC..147FF; generate_oem.py. */']
for i,name in enumerate(['ENGINE_A','ENGINE_B','ENGINE_MAX','LOAD','COUNT','COOLANT','SPEED_A','SPEED_B']):
    vss_header.append(f'#define OEM_VSS_{name} {data[0x1001F+i]}U')
for name,offset in [('LOW',0x147FC),('HIGH',0x147FE)]:
    vss_header.append(f'#define OEM_VSS_{name} {cal.word(offset)}U')
vss_header.append(f'#define OEM_VSS_MAX_BATCH {data[0x1001E]}U')
for name,offset in [('PULSE_SCALE',0x147F8),('FALLBACK',0x147FA),
                    ('PHYSICAL_FILTER',0x14800),('SOURCE_FILTER',0x14802)]:
    vss_header.append(f'#define OEM_VSS_{name} {cal.word(offset)}U')
(ROOT/'include/oem_vss_data.h').write_text('\n'.join(vss_header)+'\n')
input_layout={'context_words':[0xF874,0x96A6,0xF8AE,0x95F2,0x95F6,0x95F4,0x95EE,
                               0x95F0,0x98C4,0xABB6,0x989C,0x9920,0x9A2E,0x9888],
              'context_bytes':[0x9507,0x9201], 'context_output':list(range(0x951B,0x9529))}
(ROOT/'docs/oem-input-layout.json').write_text(json.dumps(input_layout,indent=2)+'\n')
calls=recover_calls(data)
direct_calls,dynamic_calls=event_callsites(calls)
ported_events={0x5B,0x61,0x65,0x68}
matrix=[]
for event,row in enumerate(rows):
    reportable=any(row)
    policy=policy_for(event,reportable)
    direct=[f'{v:05X}' for v in direct_calls.get(event,())]
    dynamic=[f'{v:05X}' for v in dynamic_calls.get(event,())]
    producer_resolution=('direct' if direct else 'bounded_dynamic' if dynamic else
                         'unresolved' if reportable else 'not_reportable')
    matrix.append(dict(event=event,report_words=[f'{v:04X}' for v in row],config_index=data[0x1186F+event],
                       reportable=reportable,mapping_proven=True,
                       producer_resolution=producer_resolution,
                       direct_callsites=direct,dynamic_callsites=dynamic,
                       standalone_applicability=policy.status,
                       standalone_allowed_subtypes=list(policy.allowed_subtypes),
                       standalone_reason=policy.reason,
                       standalone_evidence=policy.evidence,
                       producer='C port with native-contract tests' if event in ported_events else 'pending',
                       runtime_integration='pending',lifecycle='pending',parity_complete=False))
(ROOT/'docs').mkdir(exist_ok=True)
(ROOT/'docs/dtc-parity.json').write_text(json.dumps({
    'rom_sha256':hashlib.sha256(data).hexdigest(),
    'shared_lifecycle': {
        'implemented_native_contracts': ['allocation','ingestion','recovery','completion','subtype',
            'phase_confirmation_healing','mil_demand','aging','clear_admission','clear_worker',
            'cycle_initialization','reconciliation','drive_phase','warmup_phase','timestamp',
            'native_iat_coolant_composition','operating_state','context_conversion','adaptive_dividers',
            'rotation_capture_period_speed','analog_publication_frontend','native_supply_voltage_composition',
            'native_vehicle_speed_diagnostic_composition','native_vehicle_speed_input_composition',
            'native_digital_input_composition','native_readiness_composition','ported_clear_composition'],
        'runtime_integration':'owner_integrated_native_inputs_pending',
        'persistence_history':'boot_foreground_shutdown_integrated_physical_release_blocked',
        'all_event_trigger_parity':False,'physical_mil_flashing':False},
    'coverage_summary': {
        'event_slots':len(rows),
        'reportable_events':sum(any(row) for row in rows),
        'distinct_report_words':len({word for row in rows for word in row if word}),
        'producer_control_flow_resolved':sum(
            any(row) and (event in direct_calls or event in dynamic_calls)
            for event,row in enumerate(rows)),
        'producer_control_flow_unresolved_events':['31'],
        'ported_monitor_producers':len(ported_events),
        'standalone_available_events':sum(
            policy_for(event,any(row)).status == 'available'
            for event,row in enumerate(rows)),
        'standalone_port_candidate_events':sum(
            any(row) and policy_for(event,True).status == 'port_candidate'
            for event,row in enumerate(rows)),
        'standalone_adaptation_candidate_events':sum(
            any(row) and policy_for(event,True).status == 'adaptation_candidate'
            for event,row in enumerate(rows)),
        'standalone_narrowband_candidate_events':sum(
            any(row) and policy_for(event,True).status == 'narrowband_candidate'
            for event,row in enumerate(rows)),
        'standalone_unresolved_events':sum(
            any(row) and policy_for(event,True).status == 'unresolved'
            for event,row in enumerate(rows)),
        'standalone_unavailable_events':sum(
            any(row) and policy_for(event,True).status == 'unavailable'
            for event,row in enumerate(rows)),
        'standalone_available_event_ids':[
            f'{event:02X}' for event,row in enumerate(rows)
            if policy_for(event,any(row)).status == 'available'
        ],
        'complete_monitor_parity':0,
    },
    'unresolved_table_driven_callsites':[
        f'{call.callsite:05X}' for call in calls
        if call.event is None and call.callsite not in TU5JP_DYNAMIC_EVENT_RULES
    ],
    'events':matrix},indent=2)+'\n')
# Native contract state layout matches the existing ROM differential tests.
addresses=sorted(set([*range(0x9505,0x950F),0x9510,0xAA5C,0x8AFC,0x8AFD,0xF86C,0x95B4,0xB03E,0xB2DA,0xB2EA,0xB2E6,0x8AFA,0x8AFE,0x9BB8,*range(0x8B00,0x8B14,2)]))
flags=[0xFD06,0xFD14,0xFD16,0xFD18,0xFD5E,0xFD6A,0xFD6C]
layout_header=['/* Generated public indices for native shared-state bindings. */',
               '#ifndef LRE_OEM_LAYOUT_H','#define LRE_OEM_LAYOUT_H']
layout_header += [f'#define OEM_CLT_{a:X} {i}U' for i,a in enumerate(addresses)]
layout_header += [f'#define OEM_FLAG_{a:X} {i}U' for i,a in enumerate(flags)]
layout_header += ['#endif']
(ROOT/'include/oem_layout.h').write_text('\n'.join(layout_header)+'\n')
header=['/* Generated native state indices and stock calibration. */']
header += [f'#define R{a:X} s->value[{i}]' for i,a in enumerate(addresses)]
header += [f'#define F{a:X} s->flags[{i}]' for i,a in enumerate(flags)]
header += ['const u16 oem_coolant_addresses[33]={'+','.join(hex(a) for a in addresses)+ '};',
           'const u16 oem_flag_addresses[7]={'+','.join(hex(a) for a in flags)+'};']
for name,values in [('coolant_raw',[cal.curve(0x19827,(i>>2)&255) if i&0x300 else cal.curve(0x19850,i&255) for i in range(1024)]),
                    ('gain_a',data[0x1D842:0x1D862]),('gain_b',data[0x1D862:0x1D882])]:
    header += [f'static const u8 {name}[{len(values)}]={{']
    header += [','.join(str(v) for v in values[i:i+24])+',' for i in range(0,len(values),24)]
    header += ['};']
(ROOT/'include/oem_data.h').write_text('\n'.join(header)+'\n')
(ROOT/'docs/oem-state-layout.json').write_text(json.dumps({'addresses':addresses,'flags':flags},indent=2)+'\n')
print(f'Generated {len(rows)} event rows, {len(addresses)} native coolant fields')
